CLASS_RESULTS = LOAD '$inputLocation' using PigStorage(',') AS (name:chararray,percentage:float,class:int);
GROUPD_CLASS_RESULTS = GROUP CLASS_RESULTS BY class;
SECOND_TOPPERS = FOREACH GROUPD_CLASS_RESULTS { SORTED1 = ORDER CLASS_RESULTS BY percentage DESC; LIMITED = LIMIT SORTED1 2; SORTED2 = ORDER LIMITED BY percentage ASC; SEC_TOPPER = LIMIT SORTED2 1; GENERATE FLATTEN(SEC_TOPPER);};
STORE SECOND_TOPPERS INTO '$outputLocation' using PigStorage(',');